# coding: utf-8

"""
    Sonatype Nexus IQ Server

    This documents the available APIs into [Sonatype Nexus IQ Server](https://www.sonatype.com/products/open-source-security-dependency-management) (also knwon as Nexus Lifecycle).   # noqa: E501

    OpenAPI spec version: 156
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class ApiReportPolicyViolationDTOV2(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        "policy_id": "str",
        "policy_name": "str",
        "policy_threat_category": "str",
        "policy_threat_level": "int",
        "policy_violation_id": "str",
        "waived": "bool",
        "grandfathered": "bool",
        "constraints": "list[ApiReportConstraintViolationDTOV2]",
    }

    attribute_map = {
        "policy_id": "policyId",
        "policy_name": "policyName",
        "policy_threat_category": "policyThreatCategory",
        "policy_threat_level": "policyThreatLevel",
        "policy_violation_id": "policyViolationId",
        "waived": "waived",
        "grandfathered": "grandfathered",
        "constraints": "constraints",
    }

    def __init__(
        self,
        policy_id=None,
        policy_name=None,
        policy_threat_category=None,
        policy_threat_level=None,
        policy_violation_id=None,
        waived=None,
        grandfathered=None,
        constraints=None,
    ):  # noqa: E501
        """ApiReportPolicyViolationDTOV2 - a model defined in Swagger"""  # noqa: E501
        self._policy_id = None
        self._policy_name = None
        self._policy_threat_category = None
        self._policy_threat_level = None
        self._policy_violation_id = None
        self._waived = None
        self._grandfathered = None
        self._constraints = None
        self.discriminator = None
        if policy_id is not None:
            self.policy_id = policy_id
        if policy_name is not None:
            self.policy_name = policy_name
        if policy_threat_category is not None:
            self.policy_threat_category = policy_threat_category
        if policy_threat_level is not None:
            self.policy_threat_level = policy_threat_level
        if policy_violation_id is not None:
            self.policy_violation_id = policy_violation_id
        if waived is not None:
            self.waived = waived
        if grandfathered is not None:
            self.grandfathered = grandfathered
        if constraints is not None:
            self.constraints = constraints

    @property
    def policy_id(self):
        """Gets the policy_id of this ApiReportPolicyViolationDTOV2.  # noqa: E501


        :return: The policy_id of this ApiReportPolicyViolationDTOV2.  # noqa: E501
        :rtype: str
        """
        return self._policy_id

    @policy_id.setter
    def policy_id(self, policy_id):
        """Sets the policy_id of this ApiReportPolicyViolationDTOV2.


        :param policy_id: The policy_id of this ApiReportPolicyViolationDTOV2.  # noqa: E501
        :type: str
        """

        self._policy_id = policy_id

    @property
    def policy_name(self):
        """Gets the policy_name of this ApiReportPolicyViolationDTOV2.  # noqa: E501


        :return: The policy_name of this ApiReportPolicyViolationDTOV2.  # noqa: E501
        :rtype: str
        """
        return self._policy_name

    @policy_name.setter
    def policy_name(self, policy_name):
        """Sets the policy_name of this ApiReportPolicyViolationDTOV2.


        :param policy_name: The policy_name of this ApiReportPolicyViolationDTOV2.  # noqa: E501
        :type: str
        """

        self._policy_name = policy_name

    @property
    def policy_threat_category(self):
        """Gets the policy_threat_category of this ApiReportPolicyViolationDTOV2.  # noqa: E501


        :return: The policy_threat_category of this ApiReportPolicyViolationDTOV2.  # noqa: E501
        :rtype: str
        """
        return self._policy_threat_category

    @policy_threat_category.setter
    def policy_threat_category(self, policy_threat_category):
        """Sets the policy_threat_category of this ApiReportPolicyViolationDTOV2.


        :param policy_threat_category: The policy_threat_category of this ApiReportPolicyViolationDTOV2.  # noqa: E501
        :type: str
        """

        self._policy_threat_category = policy_threat_category

    @property
    def policy_threat_level(self):
        """Gets the policy_threat_level of this ApiReportPolicyViolationDTOV2.  # noqa: E501


        :return: The policy_threat_level of this ApiReportPolicyViolationDTOV2.  # noqa: E501
        :rtype: int
        """
        return self._policy_threat_level

    @policy_threat_level.setter
    def policy_threat_level(self, policy_threat_level):
        """Sets the policy_threat_level of this ApiReportPolicyViolationDTOV2.


        :param policy_threat_level: The policy_threat_level of this ApiReportPolicyViolationDTOV2.  # noqa: E501
        :type: int
        """

        self._policy_threat_level = policy_threat_level

    @property
    def policy_violation_id(self):
        """Gets the policy_violation_id of this ApiReportPolicyViolationDTOV2.  # noqa: E501


        :return: The policy_violation_id of this ApiReportPolicyViolationDTOV2.  # noqa: E501
        :rtype: str
        """
        return self._policy_violation_id

    @policy_violation_id.setter
    def policy_violation_id(self, policy_violation_id):
        """Sets the policy_violation_id of this ApiReportPolicyViolationDTOV2.


        :param policy_violation_id: The policy_violation_id of this ApiReportPolicyViolationDTOV2.  # noqa: E501
        :type: str
        """

        self._policy_violation_id = policy_violation_id

    @property
    def waived(self):
        """Gets the waived of this ApiReportPolicyViolationDTOV2.  # noqa: E501


        :return: The waived of this ApiReportPolicyViolationDTOV2.  # noqa: E501
        :rtype: bool
        """
        return self._waived

    @waived.setter
    def waived(self, waived):
        """Sets the waived of this ApiReportPolicyViolationDTOV2.


        :param waived: The waived of this ApiReportPolicyViolationDTOV2.  # noqa: E501
        :type: bool
        """

        self._waived = waived

    @property
    def grandfathered(self):
        """Gets the grandfathered of this ApiReportPolicyViolationDTOV2.  # noqa: E501


        :return: The grandfathered of this ApiReportPolicyViolationDTOV2.  # noqa: E501
        :rtype: bool
        """
        return self._grandfathered

    @grandfathered.setter
    def grandfathered(self, grandfathered):
        """Sets the grandfathered of this ApiReportPolicyViolationDTOV2.


        :param grandfathered: The grandfathered of this ApiReportPolicyViolationDTOV2.  # noqa: E501
        :type: bool
        """

        self._grandfathered = grandfathered

    @property
    def constraints(self):
        """Gets the constraints of this ApiReportPolicyViolationDTOV2.  # noqa: E501


        :return: The constraints of this ApiReportPolicyViolationDTOV2.  # noqa: E501
        :rtype: list[ApiReportConstraintViolationDTOV2]
        """
        return self._constraints

    @constraints.setter
    def constraints(self, constraints):
        """Sets the constraints of this ApiReportPolicyViolationDTOV2.


        :param constraints: The constraints of this ApiReportPolicyViolationDTOV2.  # noqa: E501
        :type: list[ApiReportConstraintViolationDTOV2]
        """

        self._constraints = constraints

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(ApiReportPolicyViolationDTOV2, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiReportPolicyViolationDTOV2):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
