# coding: utf-8

"""
    Sonatype Nexus IQ Server

    This documents the available APIs into [Sonatype Nexus IQ Server](https://www.sonatype.com/products/open-source-security-dependency-management) (also knwon as Nexus Lifecycle).   # noqa: E501

    OpenAPI spec version: 156
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class ApiRepositoryDTO(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {"repository_id": "str", "public_id": "str", "format": "str"}

    attribute_map = {
        "repository_id": "repositoryId",
        "public_id": "publicId",
        "format": "format",
    }

    def __init__(self, repository_id=None, public_id=None, format=None):  # noqa: E501
        """ApiRepositoryDTO - a model defined in Swagger"""  # noqa: E501
        self._repository_id = None
        self._public_id = None
        self._format = None
        self.discriminator = None
        if repository_id is not None:
            self.repository_id = repository_id
        if public_id is not None:
            self.public_id = public_id
        if format is not None:
            self.format = format

    @property
    def repository_id(self):
        """Gets the repository_id of this ApiRepositoryDTO.  # noqa: E501


        :return: The repository_id of this ApiRepositoryDTO.  # noqa: E501
        :rtype: str
        """
        return self._repository_id

    @repository_id.setter
    def repository_id(self, repository_id):
        """Sets the repository_id of this ApiRepositoryDTO.


        :param repository_id: The repository_id of this ApiRepositoryDTO.  # noqa: E501
        :type: str
        """

        self._repository_id = repository_id

    @property
    def public_id(self):
        """Gets the public_id of this ApiRepositoryDTO.  # noqa: E501


        :return: The public_id of this ApiRepositoryDTO.  # noqa: E501
        :rtype: str
        """
        return self._public_id

    @public_id.setter
    def public_id(self, public_id):
        """Sets the public_id of this ApiRepositoryDTO.


        :param public_id: The public_id of this ApiRepositoryDTO.  # noqa: E501
        :type: str
        """

        self._public_id = public_id

    @property
    def format(self):
        """Gets the format of this ApiRepositoryDTO.  # noqa: E501


        :return: The format of this ApiRepositoryDTO.  # noqa: E501
        :rtype: str
        """
        return self._format

    @format.setter
    def format(self, format):
        """Sets the format of this ApiRepositoryDTO.


        :param format: The format of this ApiRepositoryDTO.  # noqa: E501
        :type: str
        """

        self._format = format

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(ApiRepositoryDTO, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiRepositoryDTO):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
