# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from common_pb2 import (
    EntityTypeValue as common_pb2___EntityTypeValue,
)

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.internal.enum_type_wrapper import (
    _EnumTypeWrapper as google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from google.protobuf.timestamp_pb2 import (
    Timestamp as google___protobuf___timestamp_pb2___Timestamp,
)

from typing import (
    Iterable as typing___Iterable,
    NewType as typing___NewType,
    Optional as typing___Optional,
    Text as typing___Text,
    cast as typing___cast,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

ConsolePropertyOverrideStatusValue = typing___NewType('ConsolePropertyOverrideStatusValue', builtin___int)
type___ConsolePropertyOverrideStatusValue = ConsolePropertyOverrideStatusValue
ConsolePropertyOverrideStatus: _ConsolePropertyOverrideStatus
class _ConsolePropertyOverrideStatus(google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[ConsolePropertyOverrideStatusValue]):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    CONSOLE_PROPERTY_OVERRIDE_STATUS_UNSPECIFIED = typing___cast(ConsolePropertyOverrideStatusValue, 0)
    CONSOLE_PROPERTY_OVERRIDE_STATUS_ENABLED = typing___cast(ConsolePropertyOverrideStatusValue, 1)
    CONSOLE_PROPERTY_OVERRIDE_STATUS_DISABLED = typing___cast(ConsolePropertyOverrideStatusValue, 2)
CONSOLE_PROPERTY_OVERRIDE_STATUS_UNSPECIFIED = typing___cast(ConsolePropertyOverrideStatusValue, 0)
CONSOLE_PROPERTY_OVERRIDE_STATUS_ENABLED = typing___cast(ConsolePropertyOverrideStatusValue, 1)
CONSOLE_PROPERTY_OVERRIDE_STATUS_DISABLED = typing___cast(ConsolePropertyOverrideStatusValue, 2)
type___ConsolePropertyOverrideStatus = ConsolePropertyOverrideStatus

class ConsolePropertyOverride(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    organization_id: typing___Text = ...
    field_id: typing___Text = ...
    display_name: typing___Text = ...
    description: typing___Text = ...
    status: type___ConsolePropertyOverrideStatusValue = ...
    entity_type: common_pb2___EntityTypeValue = ...
    updated_by_organization_user_id: typing___Text = ...

    @property
    def created_at(self) -> google___protobuf___timestamp_pb2___Timestamp: ...

    @property
    def updated_at(self) -> google___protobuf___timestamp_pb2___Timestamp: ...

    @property
    def deleted_at(self) -> google___protobuf___timestamp_pb2___Timestamp: ...

    def __init__(self,
        *,
        organization_id : typing___Optional[typing___Text] = None,
        field_id : typing___Optional[typing___Text] = None,
        display_name : typing___Optional[typing___Text] = None,
        description : typing___Optional[typing___Text] = None,
        status : typing___Optional[type___ConsolePropertyOverrideStatusValue] = None,
        entity_type : typing___Optional[common_pb2___EntityTypeValue] = None,
        updated_by_organization_user_id : typing___Optional[typing___Text] = None,
        created_at : typing___Optional[google___protobuf___timestamp_pb2___Timestamp] = None,
        updated_at : typing___Optional[google___protobuf___timestamp_pb2___Timestamp] = None,
        deleted_at : typing___Optional[google___protobuf___timestamp_pb2___Timestamp] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"created_at",b"created_at",u"deleted_at",b"deleted_at",u"updated_at",b"updated_at"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"created_at",b"created_at",u"deleted_at",b"deleted_at",u"description",b"description",u"display_name",b"display_name",u"entity_type",b"entity_type",u"field_id",b"field_id",u"organization_id",b"organization_id",u"status",b"status",u"updated_at",b"updated_at",u"updated_by_organization_user_id",b"updated_by_organization_user_id"]) -> None: ...
type___ConsolePropertyOverride = ConsolePropertyOverride

class ConsolePropertyOverrideList(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def properties(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___ConsolePropertyOverride]: ...

    def __init__(self,
        *,
        properties : typing___Optional[typing___Iterable[type___ConsolePropertyOverride]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"properties",b"properties"]) -> None: ...
type___ConsolePropertyOverrideList = ConsolePropertyOverrideList

class GetConsolePropertyOverrideRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    field_id: typing___Text = ...
    entity_type: common_pb2___EntityTypeValue = ...

    def __init__(self,
        *,
        field_id : typing___Optional[typing___Text] = None,
        entity_type : typing___Optional[common_pb2___EntityTypeValue] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"entity_type",b"entity_type",u"field_id",b"field_id"]) -> None: ...
type___GetConsolePropertyOverrideRequest = GetConsolePropertyOverrideRequest

class PutConsolePropertyOverrideRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def property(self) -> type___ConsolePropertyOverride: ...

    def __init__(self,
        *,
        property : typing___Optional[type___ConsolePropertyOverride] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"property",b"property"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"property",b"property"]) -> None: ...
type___PutConsolePropertyOverrideRequest = PutConsolePropertyOverrideRequest

class PropertySearchResponseValue(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    value: typing___Text = ...
    count: builtin___int = ...

    def __init__(self,
        *,
        value : typing___Optional[typing___Text] = None,
        count : typing___Optional[builtin___int] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"count",b"count",u"value",b"value"]) -> None: ...
type___PropertySearchResponseValue = PropertySearchResponseValue

class GetPropertySearchRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    organization_id: typing___Text = ...
    entity_type: common_pb2___EntityTypeValue = ...
    field: typing___Text = ...
    query: typing___Text = ...

    def __init__(self,
        *,
        organization_id : typing___Optional[typing___Text] = None,
        entity_type : typing___Optional[common_pb2___EntityTypeValue] = None,
        field : typing___Optional[typing___Text] = None,
        query : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"entity_type",b"entity_type",u"field",b"field",u"organization_id",b"organization_id",u"query",b"query"]) -> None: ...
type___GetPropertySearchRequest = GetPropertySearchRequest

class GetPropertySearchResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    processing_time_ms: builtin___int = ...
    timed_out: builtin___bool = ...

    @property
    def results(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___PropertySearchResponseValue]: ...

    def __init__(self,
        *,
        results : typing___Optional[typing___Iterable[type___PropertySearchResponseValue]] = None,
        processing_time_ms : typing___Optional[builtin___int] = None,
        timed_out : typing___Optional[builtin___bool] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"processing_time_ms",b"processing_time_ms",u"results",b"results",u"timed_out",b"timed_out"]) -> None: ...
type___GetPropertySearchResponse = GetPropertySearchResponse
