# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ovmsclient/tfs_compat/protos/tensorflow/core/protobuf/extension_type_variant.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ovmsclient.tfs_compat.protos.tensorflow.core.protobuf import struct_pb2 as ovmsclient_dot_tfs__compat_dot_protos_dot_tensorflow_dot_core_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nRovmsclient/tfs_compat/protos/tensorflow/core/protobuf/extension_type_variant.proto\x12\novmsclient\x1a\x42ovmsclient/tfs_compat/protos/tensorflow/core/protobuf/struct.proto\"R\n\x1c\x45xtensionTypeVariantMetadata\x12\x32\n\x0ftype_spec_proto\x18\x01 \x01(\x0b\x32\x19.ovmsclient.TypeSpecProtob\x06proto3')



_EXTENSIONTYPEVARIANTMETADATA = DESCRIPTOR.message_types_by_name['ExtensionTypeVariantMetadata']
ExtensionTypeVariantMetadata = _reflection.GeneratedProtocolMessageType('ExtensionTypeVariantMetadata', (_message.Message,), {
  'DESCRIPTOR' : _EXTENSIONTYPEVARIANTMETADATA,
  '__module__' : 'ovmsclient.tfs_compat.protos.tensorflow.core.protobuf.extension_type_variant_pb2'
  # @@protoc_insertion_point(class_scope:ovmsclient.ExtensionTypeVariantMetadata)
  })
_sym_db.RegisterMessage(ExtensionTypeVariantMetadata)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EXTENSIONTYPEVARIANTMETADATA._serialized_start=166
  _EXTENSIONTYPEVARIANTMETADATA._serialized_end=248
# @@protoc_insertion_point(module_scope)
