
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-06-08T10:37:39+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "7da300f0ffed896ca8e25ecc03fb3fe543bd9730",
 "version": "1.0.0rc8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
