from StrangeSerializerLab3.AdditionalFunctions import AdditionalFunctions
from StrangeSerializerLab3.AdditionalFunctions import CODE_PROPS
from StrangeSerializerLab3.AdditionalFunctions import UNIQUE_TYPES
from StrangeSerializerLab3.StrangeJSON.StrangeJsonSerializer import StrangeJsonSerializer
from StrangeSerializerLab3.StrangeJSON.StrangeJsonSerializer import INF_LITERAL, NAN_LITERAL, TRUE_LITERAL, FALSE_LITERAL, NULL_LITERAL, INT_PATTERN, FLOAT_PATTERN, BOOL_PATTERN, STRING_PATTERN, NULL_PATTERN, ELEMENTARY_TYPES_PATTERN, ARRAY_PATTERN, OBJECT_PATTERN, VALUE_PATTERN
from StrangeSerializerLab3.StrangeXML.StrangeXmlSerializer import StrangeXmlSerializer
from StrangeSerializerLab3.StrangeXML.StrangeXmlSerializer import NONE_LITERAL, KEY_GROUP_NAME, VALUE_GROUP_NAME, XML_SCHEME_SOURCE, XML_SCHEME_PATTERN, ELEMENTARY_NAMES_PATTERN, XML_ELEMENT_PATTERN, FIRST_XML_ELEMENT_PATTERN
