# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .access_list import *
from .cdc import *
from .database import *
from .get_access_list import *
from .get_astra_database import *
from .get_astra_databases import *
from .get_available_regions import *
from .get_keyspace import *
from .get_keyspaces import *
from .get_private_link_endpoints import *
from .get_private_links import *
from .get_role import *
from .get_roles import *
from .get_secure_connect_bundle_url import *
from .get_streaming_tenant_tokens import *
from .get_users import *
from .keyspace import *
from .private_link import *
from .private_link_endpoint import *
from .provider import *
from .role import *
from .streaming_sink import *
from .streaming_tenant import *
from .streaming_topic import *
from .table import *
from .token import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumiverse_astra.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumiverse_astra.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "astra",
  "mod": "index/accessList",
  "fqn": "pulumiverse_astra",
  "classes": {
   "astra:index/accessList:AccessList": "AccessList"
  }
 },
 {
  "pkg": "astra",
  "mod": "index/cdc",
  "fqn": "pulumiverse_astra",
  "classes": {
   "astra:index/cdc:Cdc": "Cdc"
  }
 },
 {
  "pkg": "astra",
  "mod": "index/database",
  "fqn": "pulumiverse_astra",
  "classes": {
   "astra:index/database:Database": "Database"
  }
 },
 {
  "pkg": "astra",
  "mod": "index/keyspace",
  "fqn": "pulumiverse_astra",
  "classes": {
   "astra:index/keyspace:Keyspace": "Keyspace"
  }
 },
 {
  "pkg": "astra",
  "mod": "index/privateLink",
  "fqn": "pulumiverse_astra",
  "classes": {
   "astra:index/privateLink:PrivateLink": "PrivateLink"
  }
 },
 {
  "pkg": "astra",
  "mod": "index/privateLinkEndpoint",
  "fqn": "pulumiverse_astra",
  "classes": {
   "astra:index/privateLinkEndpoint:PrivateLinkEndpoint": "PrivateLinkEndpoint"
  }
 },
 {
  "pkg": "astra",
  "mod": "index/role",
  "fqn": "pulumiverse_astra",
  "classes": {
   "astra:index/role:Role": "Role"
  }
 },
 {
  "pkg": "astra",
  "mod": "index/streamingSink",
  "fqn": "pulumiverse_astra",
  "classes": {
   "astra:index/streamingSink:StreamingSink": "StreamingSink"
  }
 },
 {
  "pkg": "astra",
  "mod": "index/streamingTenant",
  "fqn": "pulumiverse_astra",
  "classes": {
   "astra:index/streamingTenant:StreamingTenant": "StreamingTenant"
  }
 },
 {
  "pkg": "astra",
  "mod": "index/streamingTopic",
  "fqn": "pulumiverse_astra",
  "classes": {
   "astra:index/streamingTopic:StreamingTopic": "StreamingTopic"
  }
 },
 {
  "pkg": "astra",
  "mod": "index/table",
  "fqn": "pulumiverse_astra",
  "classes": {
   "astra:index/table:Table": "Table"
  }
 },
 {
  "pkg": "astra",
  "mod": "index/token",
  "fqn": "pulumiverse_astra",
  "classes": {
   "astra:index/token:Token": "Token"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "astra",
  "token": "pulumi:providers:astra",
  "fqn": "pulumiverse_astra",
  "class": "Provider"
 }
]
"""
)
