# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Statistics.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Statistics.proto',
  package='data.stat',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10Statistics.proto\x12\tdata.stat\x1a\x1fgoogle/protobuf/timestamp.proto\"f\n\x11\x44\x61tasetStatistics\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0bnum_example\x18\x02 \x01(\x04\x12.\n\x08\x66\x65\x61tures\x18\x03 \x03(\x0b\x32\x1c.data.stat.FeatureStatistics\"\xf6\x01\n\x11\x46\x65\x61tureStatistics\x12\x0c\n\x04name\x18\x01 \x01(\t\x12/\n\x04type\x18\x02 \x01(\x0e\x32!.data.stat.FeatureStatistics.Type\x12\x10\n\x08nullable\x18\x03 \x01(\x08\x12\x1a\n\x12\x66\x65\x61ture_importance\x18\x04 \x01(\x01\x12\x35\n\rnumeric_stats\x18\x05 \x01(\x0b\x32\x1c.data.stat.NumericStatisticsH\x00\"4\n\x04Type\x12\x07\n\x03INT\x10\x00\x12\t\n\x05\x46LOAT\x10\x01\x12\n\n\x06STRING\x10\x02\x12\x0c\n\x08\x44\x41TETIME\x10\x03\x42\x07\n\x05stats\"\xa8\x02\n\x11NumericStatistics\x12\x12\n\nnum_unique\x18\x01 \x01(\x04\x12\x0c\n\x04mean\x18\x02 \x01(\x01\x12\x0f\n\x07std_dev\x18\x03 \x01(\x01\x12\x18\n\x10percent_of_nulls\x18\x04 \x01(\x01\x12/\n\x04\x66req\x18\x05 \x03(\x0b\x32!.data.stat.NumericStatistics.Freq\x12\x11\n\tmax_value\x18\x06 \x01(\x01\x12\x11\n\tmin_value\x18\x07 \x01(\x01\x12\"\n\x04hist\x18\x08 \x01(\x0b\x32\x14.data.stat.Histogram\x12\x13\n\x0bpercentiles\x18\t \x03(\x01\x12\x0c\n\x04mode\x18\n \x01(\x01\x1a(\n\x04\x46req\x12\r\n\x05value\x18\x01 \x01(\x01\x12\x11\n\tfrequency\x18\x02 \x01(\x01\"\xd9\x01\n\tHistogram\x12\x30\n\x04type\x18\x01 \x01(\x0e\x32\".data.stat.Histogram.HistogramType\x12,\n\x07\x62uckets\x18\x02 \x03(\x0b\x32\x1b.data.stat.Histogram.Bucket\x1a>\n\x06\x42ucket\x12\x11\n\tlow_value\x18\x01 \x01(\x01\x12\x12\n\nhigh_value\x18\x02 \x01(\x01\x12\r\n\x05\x63ount\x18\x03 \x01(\x04\",\n\rHistogramType\x12\x0c\n\x08STANDARD\x10\x00\x12\r\n\tQUANTILES\x10\x01\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])



_FEATURESTATISTICS_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='data.stat.FeatureStatistics.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FLOAT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STRING', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DATETIME', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=354,
  serialized_end=406,
)
_sym_db.RegisterEnumDescriptor(_FEATURESTATISTICS_TYPE)

_HISTOGRAM_HISTOGRAMTYPE = _descriptor.EnumDescriptor(
  name='HistogramType',
  full_name='data.stat.Histogram.HistogramType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STANDARD', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='QUANTILES', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=890,
  serialized_end=934,
)
_sym_db.RegisterEnumDescriptor(_HISTOGRAM_HISTOGRAMTYPE)


_DATASETSTATISTICS = _descriptor.Descriptor(
  name='DatasetStatistics',
  full_name='data.stat.DatasetStatistics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='data.stat.DatasetStatistics.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_example', full_name='data.stat.DatasetStatistics.num_example', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='features', full_name='data.stat.DatasetStatistics.features', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=166,
)


_FEATURESTATISTICS = _descriptor.Descriptor(
  name='FeatureStatistics',
  full_name='data.stat.FeatureStatistics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='data.stat.FeatureStatistics.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='data.stat.FeatureStatistics.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nullable', full_name='data.stat.FeatureStatistics.nullable', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='feature_importance', full_name='data.stat.FeatureStatistics.feature_importance', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='numeric_stats', full_name='data.stat.FeatureStatistics.numeric_stats', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _FEATURESTATISTICS_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='stats', full_name='data.stat.FeatureStatistics.stats',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=169,
  serialized_end=415,
)


_NUMERICSTATISTICS_FREQ = _descriptor.Descriptor(
  name='Freq',
  full_name='data.stat.NumericStatistics.Freq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='data.stat.NumericStatistics.Freq.value', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frequency', full_name='data.stat.NumericStatistics.Freq.frequency', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=674,
  serialized_end=714,
)

_NUMERICSTATISTICS = _descriptor.Descriptor(
  name='NumericStatistics',
  full_name='data.stat.NumericStatistics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_unique', full_name='data.stat.NumericStatistics.num_unique', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mean', full_name='data.stat.NumericStatistics.mean', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='std_dev', full_name='data.stat.NumericStatistics.std_dev', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='percent_of_nulls', full_name='data.stat.NumericStatistics.percent_of_nulls', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='freq', full_name='data.stat.NumericStatistics.freq', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_value', full_name='data.stat.NumericStatistics.max_value', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='min_value', full_name='data.stat.NumericStatistics.min_value', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hist', full_name='data.stat.NumericStatistics.hist', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='percentiles', full_name='data.stat.NumericStatistics.percentiles', index=8,
      number=9, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mode', full_name='data.stat.NumericStatistics.mode', index=9,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_NUMERICSTATISTICS_FREQ, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=418,
  serialized_end=714,
)


_HISTOGRAM_BUCKET = _descriptor.Descriptor(
  name='Bucket',
  full_name='data.stat.Histogram.Bucket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='low_value', full_name='data.stat.Histogram.Bucket.low_value', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='high_value', full_name='data.stat.Histogram.Bucket.high_value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='count', full_name='data.stat.Histogram.Bucket.count', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=826,
  serialized_end=888,
)

_HISTOGRAM = _descriptor.Descriptor(
  name='Histogram',
  full_name='data.stat.Histogram',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='data.stat.Histogram.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='buckets', full_name='data.stat.Histogram.buckets', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_HISTOGRAM_BUCKET, ],
  enum_types=[
    _HISTOGRAM_HISTOGRAMTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=717,
  serialized_end=934,
)

_DATASETSTATISTICS.fields_by_name['features'].message_type = _FEATURESTATISTICS
_FEATURESTATISTICS.fields_by_name['type'].enum_type = _FEATURESTATISTICS_TYPE
_FEATURESTATISTICS.fields_by_name['numeric_stats'].message_type = _NUMERICSTATISTICS
_FEATURESTATISTICS_TYPE.containing_type = _FEATURESTATISTICS
_FEATURESTATISTICS.oneofs_by_name['stats'].fields.append(
  _FEATURESTATISTICS.fields_by_name['numeric_stats'])
_FEATURESTATISTICS.fields_by_name['numeric_stats'].containing_oneof = _FEATURESTATISTICS.oneofs_by_name['stats']
_NUMERICSTATISTICS_FREQ.containing_type = _NUMERICSTATISTICS
_NUMERICSTATISTICS.fields_by_name['freq'].message_type = _NUMERICSTATISTICS_FREQ
_NUMERICSTATISTICS.fields_by_name['hist'].message_type = _HISTOGRAM
_HISTOGRAM_BUCKET.containing_type = _HISTOGRAM
_HISTOGRAM.fields_by_name['type'].enum_type = _HISTOGRAM_HISTOGRAMTYPE
_HISTOGRAM.fields_by_name['buckets'].message_type = _HISTOGRAM_BUCKET
_HISTOGRAM_HISTOGRAMTYPE.containing_type = _HISTOGRAM
DESCRIPTOR.message_types_by_name['DatasetStatistics'] = _DATASETSTATISTICS
DESCRIPTOR.message_types_by_name['FeatureStatistics'] = _FEATURESTATISTICS
DESCRIPTOR.message_types_by_name['NumericStatistics'] = _NUMERICSTATISTICS
DESCRIPTOR.message_types_by_name['Histogram'] = _HISTOGRAM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DatasetStatistics = _reflection.GeneratedProtocolMessageType('DatasetStatistics', (_message.Message,), {
  'DESCRIPTOR' : _DATASETSTATISTICS,
  '__module__' : 'Statistics_pb2'
  # @@protoc_insertion_point(class_scope:data.stat.DatasetStatistics)
  })
_sym_db.RegisterMessage(DatasetStatistics)

FeatureStatistics = _reflection.GeneratedProtocolMessageType('FeatureStatistics', (_message.Message,), {
  'DESCRIPTOR' : _FEATURESTATISTICS,
  '__module__' : 'Statistics_pb2'
  # @@protoc_insertion_point(class_scope:data.stat.FeatureStatistics)
  })
_sym_db.RegisterMessage(FeatureStatistics)

NumericStatistics = _reflection.GeneratedProtocolMessageType('NumericStatistics', (_message.Message,), {

  'Freq' : _reflection.GeneratedProtocolMessageType('Freq', (_message.Message,), {
    'DESCRIPTOR' : _NUMERICSTATISTICS_FREQ,
    '__module__' : 'Statistics_pb2'
    # @@protoc_insertion_point(class_scope:data.stat.NumericStatistics.Freq)
    })
  ,
  'DESCRIPTOR' : _NUMERICSTATISTICS,
  '__module__' : 'Statistics_pb2'
  # @@protoc_insertion_point(class_scope:data.stat.NumericStatistics)
  })
_sym_db.RegisterMessage(NumericStatistics)
_sym_db.RegisterMessage(NumericStatistics.Freq)

Histogram = _reflection.GeneratedProtocolMessageType('Histogram', (_message.Message,), {

  'Bucket' : _reflection.GeneratedProtocolMessageType('Bucket', (_message.Message,), {
    'DESCRIPTOR' : _HISTOGRAM_BUCKET,
    '__module__' : 'Statistics_pb2'
    # @@protoc_insertion_point(class_scope:data.stat.Histogram.Bucket)
    })
  ,
  'DESCRIPTOR' : _HISTOGRAM,
  '__module__' : 'Statistics_pb2'
  # @@protoc_insertion_point(class_scope:data.stat.Histogram)
  })
_sym_db.RegisterMessage(Histogram)
_sym_db.RegisterMessage(Histogram.Bucket)


# @@protoc_insertion_point(module_scope)
