# coding: utf-8

"""
    Sonatype Nexus IQ Server

    This documents the available APIs into [Sonatype Nexus IQ Server](https://www.sonatype.com/products/open-source-security-dependency-management) (also knwon as Nexus Lifecycle).   # noqa: E501

    OpenAPI spec version: 156
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class ApiLabelDTO(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        "id": "str",
        "label": "str",
        "description": "str",
        "color": "str",
        "owner_id": "str",
        "owner_type": "str",
    }

    attribute_map = {
        "id": "id",
        "label": "label",
        "description": "description",
        "color": "color",
        "owner_id": "ownerId",
        "owner_type": "ownerType",
    }

    def __init__(
        self,
        id=None,
        label=None,
        description=None,
        color=None,
        owner_id=None,
        owner_type=None,
    ):  # noqa: E501
        """ApiLabelDTO - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._label = None
        self._description = None
        self._color = None
        self._owner_id = None
        self._owner_type = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if label is not None:
            self.label = label
        if description is not None:
            self.description = description
        if color is not None:
            self.color = color
        if owner_id is not None:
            self.owner_id = owner_id
        if owner_type is not None:
            self.owner_type = owner_type

    @property
    def id(self):
        """Gets the id of this ApiLabelDTO.  # noqa: E501


        :return: The id of this ApiLabelDTO.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ApiLabelDTO.


        :param id: The id of this ApiLabelDTO.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def label(self):
        """Gets the label of this ApiLabelDTO.  # noqa: E501


        :return: The label of this ApiLabelDTO.  # noqa: E501
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this ApiLabelDTO.


        :param label: The label of this ApiLabelDTO.  # noqa: E501
        :type: str
        """

        self._label = label

    @property
    def description(self):
        """Gets the description of this ApiLabelDTO.  # noqa: E501


        :return: The description of this ApiLabelDTO.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ApiLabelDTO.


        :param description: The description of this ApiLabelDTO.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def color(self):
        """Gets the color of this ApiLabelDTO.  # noqa: E501


        :return: The color of this ApiLabelDTO.  # noqa: E501
        :rtype: str
        """
        return self._color

    @color.setter
    def color(self, color):
        """Sets the color of this ApiLabelDTO.


        :param color: The color of this ApiLabelDTO.  # noqa: E501
        :type: str
        """

        self._color = color

    @property
    def owner_id(self):
        """Gets the owner_id of this ApiLabelDTO.  # noqa: E501


        :return: The owner_id of this ApiLabelDTO.  # noqa: E501
        :rtype: str
        """
        return self._owner_id

    @owner_id.setter
    def owner_id(self, owner_id):
        """Sets the owner_id of this ApiLabelDTO.


        :param owner_id: The owner_id of this ApiLabelDTO.  # noqa: E501
        :type: str
        """

        self._owner_id = owner_id

    @property
    def owner_type(self):
        """Gets the owner_type of this ApiLabelDTO.  # noqa: E501


        :return: The owner_type of this ApiLabelDTO.  # noqa: E501
        :rtype: str
        """
        return self._owner_type

    @owner_type.setter
    def owner_type(self, owner_type):
        """Sets the owner_type of this ApiLabelDTO.


        :param owner_type: The owner_type of this ApiLabelDTO.  # noqa: E501
        :type: str
        """

        self._owner_type = owner_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(ApiLabelDTO, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiLabelDTO):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
