# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from custom_entity_pb2 import (
    CustomEntityDefinition as custom_entity_pb2___CustomEntityDefinition,
)

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class GetCustomEntityDefinitionsRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    custom_entity_definition_id: typing___Text = ...
    slug: typing___Text = ...

    def __init__(self,
        *,
        custom_entity_definition_id : typing___Optional[typing___Text] = None,
        slug : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"custom_entity_definition_id",b"custom_entity_definition_id",u"id",b"id",u"slug",b"slug"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"custom_entity_definition_id",b"custom_entity_definition_id",u"id",b"id",u"slug",b"slug"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions___Literal[u"id",b"id"]) -> typing_extensions___Literal["custom_entity_definition_id","slug"]: ...
type___GetCustomEntityDefinitionsRequest = GetCustomEntityDefinitionsRequest

class GetCustomEntityDefinitionsResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def custom_entity_definitions(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[custom_entity_pb2___CustomEntityDefinition]: ...

    def __init__(self,
        *,
        custom_entity_definitions : typing___Optional[typing___Iterable[custom_entity_pb2___CustomEntityDefinition]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"custom_entity_definitions",b"custom_entity_definitions"]) -> None: ...
type___GetCustomEntityDefinitionsResponse = GetCustomEntityDefinitionsResponse

class SaveCustomEntityDefinitionRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def custom_entity_definition(self) -> custom_entity_pb2___CustomEntityDefinition: ...

    def __init__(self,
        *,
        custom_entity_definition : typing___Optional[custom_entity_pb2___CustomEntityDefinition] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"custom_entity_definition",b"custom_entity_definition"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"custom_entity_definition",b"custom_entity_definition"]) -> None: ...
type___SaveCustomEntityDefinitionRequest = SaveCustomEntityDefinitionRequest

class SaveCustomEntityDefinitionResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def custom_entity_definition(self) -> custom_entity_pb2___CustomEntityDefinition: ...

    def __init__(self,
        *,
        custom_entity_definition : typing___Optional[custom_entity_pb2___CustomEntityDefinition] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"custom_entity_definition",b"custom_entity_definition"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"custom_entity_definition",b"custom_entity_definition"]) -> None: ...
type___SaveCustomEntityDefinitionResponse = SaveCustomEntityDefinitionResponse

class DeleteCustomEntityDefinitionRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    custom_entity_definition_id: typing___Text = ...

    def __init__(self,
        *,
        custom_entity_definition_id : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"custom_entity_definition_id",b"custom_entity_definition_id"]) -> None: ...
type___DeleteCustomEntityDefinitionRequest = DeleteCustomEntityDefinitionRequest
