# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.internal.enum_type_wrapper import (
    _EnumTypeWrapper as google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from google.protobuf.timestamp_pb2 import (
    Timestamp as google___protobuf___timestamp_pb2___Timestamp,
)

from integration_pb2 import (
    Integration as integration_pb2___Integration,
)

from typing import (
    Iterable as typing___Iterable,
    Mapping as typing___Mapping,
    MutableMapping as typing___MutableMapping,
    NewType as typing___NewType,
    Optional as typing___Optional,
    Text as typing___Text,
    cast as typing___cast,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

ImportLogStatusValue = typing___NewType('ImportLogStatusValue', builtin___int)
type___ImportLogStatusValue = ImportLogStatusValue
ImportLogStatus: _ImportLogStatus
class _ImportLogStatus(google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[ImportLogStatusValue]):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    IMPORT_LOG_STATUS_UNSPECIFIED = typing___cast(ImportLogStatusValue, 0)
    IMPORT_LOG_STATUS_SUCCESS = typing___cast(ImportLogStatusValue, 1)
    IMPORT_LOG_STATUS_FAILURE_GENERIC = typing___cast(ImportLogStatusValue, 2)
    IMPORT_LOG_STATUS_FAILURE_CREDENTIALS = typing___cast(ImportLogStatusValue, 3)
IMPORT_LOG_STATUS_UNSPECIFIED = typing___cast(ImportLogStatusValue, 0)
IMPORT_LOG_STATUS_SUCCESS = typing___cast(ImportLogStatusValue, 1)
IMPORT_LOG_STATUS_FAILURE_GENERIC = typing___cast(ImportLogStatusValue, 2)
IMPORT_LOG_STATUS_FAILURE_CREDENTIALS = typing___cast(ImportLogStatusValue, 3)
type___ImportLogStatus = ImportLogStatus

class ImportLog(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class AdditionalInformationEntry(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        key: typing___Text = ...
        value: typing___Text = ...

        def __init__(self,
            *,
            key : typing___Optional[typing___Text] = None,
            value : typing___Optional[typing___Text] = None,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"key",b"key",u"value",b"value"]) -> None: ...
    type___AdditionalInformationEntry = AdditionalInformationEntry

    status: type___ImportLogStatusValue = ...
    status_message: typing___Text = ...
    duration_seconds: builtin___int = ...

    @property
    def import_started_at(self) -> google___protobuf___timestamp_pb2___Timestamp: ...

    @property
    def integration(self) -> integration_pb2___Integration: ...

    @property
    def additional_information(self) -> typing___MutableMapping[typing___Text, typing___Text]: ...

    def __init__(self,
        *,
        status : typing___Optional[type___ImportLogStatusValue] = None,
        status_message : typing___Optional[typing___Text] = None,
        import_started_at : typing___Optional[google___protobuf___timestamp_pb2___Timestamp] = None,
        duration_seconds : typing___Optional[builtin___int] = None,
        integration : typing___Optional[integration_pb2___Integration] = None,
        additional_information : typing___Optional[typing___Mapping[typing___Text, typing___Text]] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"import_started_at",b"import_started_at",u"integration",b"integration"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"additional_information",b"additional_information",u"duration_seconds",b"duration_seconds",u"import_started_at",b"import_started_at",u"integration",b"integration",u"status",b"status",u"status_message",b"status_message"]) -> None: ...
type___ImportLog = ImportLog

class GetImportLogsRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    organization_id: typing___Text = ...
    instance_id: typing___Text = ...
    hits_per_page: builtin___int = ...
    page: builtin___int = ...
    cursor: typing___Text = ...

    def __init__(self,
        *,
        organization_id : typing___Optional[typing___Text] = None,
        instance_id : typing___Optional[typing___Text] = None,
        hits_per_page : typing___Optional[builtin___int] = None,
        page : typing___Optional[builtin___int] = None,
        cursor : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"cursor",b"cursor",u"hits_per_page",b"hits_per_page",u"instance_id",b"instance_id",u"organization_id",b"organization_id",u"page",b"page"]) -> None: ...
type___GetImportLogsRequest = GetImportLogsRequest

class GetImportLogsResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    cursor: typing___Text = ...
    hits_per_page: builtin___int = ...
    page: builtin___int = ...

    @property
    def logs(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___ImportLog]: ...

    def __init__(self,
        *,
        logs : typing___Optional[typing___Iterable[type___ImportLog]] = None,
        cursor : typing___Optional[typing___Text] = None,
        hits_per_page : typing___Optional[builtin___int] = None,
        page : typing___Optional[builtin___int] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"cursor",b"cursor",u"hits_per_page",b"hits_per_page",u"logs",b"logs",u"page",b"page"]) -> None: ...
type___GetImportLogsResponse = GetImportLogsResponse
