# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from common_pb2 import (
    EntityTypeValue as common_pb2___EntityTypeValue,
)

from condition_pb2 import (
    AbsoluteTimeRange as condition_pb2___AbsoluteTimeRange,
    ConditionGroup as condition_pb2___ConditionGroup,
    ConditionOrGroup as condition_pb2___ConditionOrGroup,
    RelativeTimeRangeValue as condition_pb2___RelativeTimeRangeValue,
)

from entity_pb2 import (
    EntityWithRelationships as entity_pb2___EntityWithRelationships,
)

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.internal.enum_type_wrapper import (
    _EnumTypeWrapper as google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from metric_pb2 import (
    AggregatedMetric as metric_pb2___AggregatedMetric,
)

from typing import (
    Iterable as typing___Iterable,
    Mapping as typing___Mapping,
    MutableMapping as typing___MutableMapping,
    NewType as typing___NewType,
    Optional as typing___Optional,
    Text as typing___Text,
    cast as typing___cast,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

SortTypeValue = typing___NewType('SortTypeValue', builtin___int)
type___SortTypeValue = SortTypeValue
SortType: _SortType
class _SortType(google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[SortTypeValue]):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    SORT_TYPE_UNSPECIFIED = typing___cast(SortTypeValue, 0)
    SORT_TYPE_PROPERTY = typing___cast(SortTypeValue, 1)
    SORT_TYPE_METRIC = typing___cast(SortTypeValue, 2)
    SORT_TYPE_DELTA = typing___cast(SortTypeValue, 3)
    SORT_TYPE_SCORING_FUNCTION = typing___cast(SortTypeValue, 4)
    SORT_TYPE_JOURNEY = typing___cast(SortTypeValue, 5)
    SORT_TYPE_PREDICTION = typing___cast(SortTypeValue, 6)
SORT_TYPE_UNSPECIFIED = typing___cast(SortTypeValue, 0)
SORT_TYPE_PROPERTY = typing___cast(SortTypeValue, 1)
SORT_TYPE_METRIC = typing___cast(SortTypeValue, 2)
SORT_TYPE_DELTA = typing___cast(SortTypeValue, 3)
SORT_TYPE_SCORING_FUNCTION = typing___cast(SortTypeValue, 4)
SORT_TYPE_JOURNEY = typing___cast(SortTypeValue, 5)
SORT_TYPE_PREDICTION = typing___cast(SortTypeValue, 6)
type___SortType = SortType

FeatureValueDistributionTypeValue = typing___NewType('FeatureValueDistributionTypeValue', builtin___int)
type___FeatureValueDistributionTypeValue = FeatureValueDistributionTypeValue
FeatureValueDistributionType: _FeatureValueDistributionType
class _FeatureValueDistributionType(google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[FeatureValueDistributionTypeValue]):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    FEATURE_VALUE_DISTRIBUTION_TYPE_UNSPECIFIED = typing___cast(FeatureValueDistributionTypeValue, 0)
    FEATURE_VALUE_DISTRIBUTION_TYPE_HISTOGRAM = typing___cast(FeatureValueDistributionTypeValue, 1)
    FEATURE_VALUE_DISTRIBUTION_TYPE_TOP_N = typing___cast(FeatureValueDistributionTypeValue, 2)
FEATURE_VALUE_DISTRIBUTION_TYPE_UNSPECIFIED = typing___cast(FeatureValueDistributionTypeValue, 0)
FEATURE_VALUE_DISTRIBUTION_TYPE_HISTOGRAM = typing___cast(FeatureValueDistributionTypeValue, 1)
FEATURE_VALUE_DISTRIBUTION_TYPE_TOP_N = typing___cast(FeatureValueDistributionTypeValue, 2)
type___FeatureValueDistributionType = FeatureValueDistributionType

class GlobalSearchRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    organization_id: typing___Text = ...
    query: typing___Text = ...
    page: builtin___int = ...
    hits_per_page: builtin___int = ...

    def __init__(self,
        *,
        organization_id : typing___Optional[typing___Text] = None,
        query : typing___Optional[typing___Text] = None,
        page : typing___Optional[builtin___int] = None,
        hits_per_page : typing___Optional[builtin___int] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"hits_per_page",b"hits_per_page",u"organization_id",b"organization_id",u"page",b"page",u"query",b"query"]) -> None: ...
type___GlobalSearchRequest = GlobalSearchRequest

class GlobalSearchResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def entities(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[entity_pb2___EntityWithRelationships]: ...

    def __init__(self,
        *,
        entities : typing___Optional[typing___Iterable[entity_pb2___EntityWithRelationships]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"entities",b"entities"]) -> None: ...
type___GlobalSearchResponse = GlobalSearchResponse

class MetricWithTimeRange(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    metric_descriptor_id: typing___Text = ...
    relative_time_range: condition_pb2___RelativeTimeRangeValue = ...

    @property
    def absolute_time_range(self) -> condition_pb2___AbsoluteTimeRange: ...

    def __init__(self,
        *,
        metric_descriptor_id : typing___Optional[typing___Text] = None,
        relative_time_range : typing___Optional[condition_pb2___RelativeTimeRangeValue] = None,
        absolute_time_range : typing___Optional[condition_pb2___AbsoluteTimeRange] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"absolute_time_range",b"absolute_time_range",u"metric_range",b"metric_range",u"relative_time_range",b"relative_time_range"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"absolute_time_range",b"absolute_time_range",u"metric_descriptor_id",b"metric_descriptor_id",u"metric_range",b"metric_range",u"relative_time_range",b"relative_time_range"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions___Literal[u"metric_range",b"metric_range"]) -> typing_extensions___Literal["relative_time_range","absolute_time_range"]: ...
type___MetricWithTimeRange = MetricWithTimeRange

class SearchSortField(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    sort_type: type___SortTypeValue = ...
    sort_field_type: typing___Text = ...
    sort_field: typing___Text = ...
    sort_asc: builtin___bool = ...

    def __init__(self,
        *,
        sort_type : typing___Optional[type___SortTypeValue] = None,
        sort_field_type : typing___Optional[typing___Text] = None,
        sort_field : typing___Optional[typing___Text] = None,
        sort_asc : typing___Optional[builtin___bool] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"sort_asc",b"sort_asc",u"sort_field",b"sort_field",u"sort_field_type",b"sort_field_type",u"sort_type",b"sort_type"]) -> None: ...
type___SearchSortField = SearchSortField

class FeatureValueDistributionRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    organization_id: typing___Text = ...
    entity_type: common_pb2___EntityTypeValue = ...
    distribution_type: type___FeatureValueDistributionTypeValue = ...
    limit: builtin___int = ...
    timeframe: condition_pb2___RelativeTimeRangeValue = ...
    field: typing___Text = ...

    @property
    def filters(self) -> condition_pb2___ConditionGroup: ...

    def __init__(self,
        *,
        organization_id : typing___Optional[typing___Text] = None,
        entity_type : typing___Optional[common_pb2___EntityTypeValue] = None,
        filters : typing___Optional[condition_pb2___ConditionGroup] = None,
        distribution_type : typing___Optional[type___FeatureValueDistributionTypeValue] = None,
        limit : typing___Optional[builtin___int] = None,
        timeframe : typing___Optional[condition_pb2___RelativeTimeRangeValue] = None,
        field : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"filters",b"filters"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"distribution_type",b"distribution_type",u"entity_type",b"entity_type",u"field",b"field",u"filters",b"filters",u"limit",b"limit",u"organization_id",b"organization_id",u"timeframe",b"timeframe"]) -> None: ...
type___FeatureValueDistributionRequest = FeatureValueDistributionRequest

class FeatureValue(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    s: typing___Text = ...
    l: builtin___int = ...
    d: builtin___float = ...
    count: builtin___int = ...
    fraction: builtin___float = ...

    def __init__(self,
        *,
        s : typing___Optional[typing___Text] = None,
        l : typing___Optional[builtin___int] = None,
        d : typing___Optional[builtin___float] = None,
        count : typing___Optional[builtin___int] = None,
        fraction : typing___Optional[builtin___float] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"d",b"d",u"l",b"l",u"s",b"s",u"value",b"value"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"count",b"count",u"d",b"d",u"fraction",b"fraction",u"l",b"l",u"s",b"s",u"value",b"value"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions___Literal[u"value",b"value"]) -> typing_extensions___Literal["s","l","d"]: ...
type___FeatureValue = FeatureValue

class FeatureValueDistributionResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    total_results: builtin___int = ...
    distinct_values_count: builtin___int = ...

    @property
    def distribution(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___FeatureValue]: ...

    def __init__(self,
        *,
        distribution : typing___Optional[typing___Iterable[type___FeatureValue]] = None,
        total_results : typing___Optional[builtin___int] = None,
        distinct_values_count : typing___Optional[builtin___int] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"distinct_values_count",b"distinct_values_count",u"distribution",b"distribution",u"total_results",b"total_results"]) -> None: ...
type___FeatureValueDistributionResponse = FeatureValueDistributionResponse

class TrendSearchRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    organization_id: typing___Text = ...
    entity_type: common_pb2___EntityTypeValue = ...
    page: builtin___int = ...
    hits_per_page: builtin___int = ...
    timeframe: condition_pb2___RelativeTimeRangeValue = ...

    @property
    def condition(self) -> condition_pb2___ConditionGroup: ...

    @property
    def columns(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[condition_pb2___ConditionOrGroup]: ...

    @property
    def sort_fields(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___SearchSortField]: ...

    def __init__(self,
        *,
        organization_id : typing___Optional[typing___Text] = None,
        entity_type : typing___Optional[common_pb2___EntityTypeValue] = None,
        condition : typing___Optional[condition_pb2___ConditionGroup] = None,
        page : typing___Optional[builtin___int] = None,
        hits_per_page : typing___Optional[builtin___int] = None,
        columns : typing___Optional[typing___Iterable[condition_pb2___ConditionOrGroup]] = None,
        sort_fields : typing___Optional[typing___Iterable[type___SearchSortField]] = None,
        timeframe : typing___Optional[condition_pb2___RelativeTimeRangeValue] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"condition",b"condition"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"columns",b"columns",u"condition",b"condition",u"entity_type",b"entity_type",u"hits_per_page",b"hits_per_page",u"organization_id",b"organization_id",u"page",b"page",u"sort_fields",b"sort_fields",u"timeframe",b"timeframe"]) -> None: ...
type___TrendSearchRequest = TrendSearchRequest

class TrendSearchEntity(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class AggregatedMetricsEntry(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        key: typing___Text = ...

        @property
        def value(self) -> metric_pb2___AggregatedMetric: ...

        def __init__(self,
            *,
            key : typing___Optional[typing___Text] = None,
            value : typing___Optional[metric_pb2___AggregatedMetric] = None,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions___Literal[u"value",b"value"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"key",b"key",u"value",b"value"]) -> None: ...
    type___AggregatedMetricsEntry = AggregatedMetricsEntry


    @property
    def ewr(self) -> entity_pb2___EntityWithRelationships: ...

    @property
    def aggregated_metrics(self) -> typing___MutableMapping[typing___Text, metric_pb2___AggregatedMetric]: ...

    def __init__(self,
        *,
        ewr : typing___Optional[entity_pb2___EntityWithRelationships] = None,
        aggregated_metrics : typing___Optional[typing___Mapping[typing___Text, metric_pb2___AggregatedMetric]] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"ewr",b"ewr"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"aggregated_metrics",b"aggregated_metrics",u"ewr",b"ewr"]) -> None: ...
type___TrendSearchEntity = TrendSearchEntity

class TrendSearchResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    total_hits: builtin___int = ...
    page: builtin___int = ...
    total_pages: builtin___int = ...
    hits_per_page: builtin___int = ...
    processing_time_ms: builtin___int = ...
    latency_index_lookup_ms: builtin___int = ...
    latency_doc_lookup_ms: builtin___int = ...

    @property
    def entities(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___TrendSearchEntity]: ...

    def __init__(self,
        *,
        total_hits : typing___Optional[builtin___int] = None,
        page : typing___Optional[builtin___int] = None,
        total_pages : typing___Optional[builtin___int] = None,
        hits_per_page : typing___Optional[builtin___int] = None,
        processing_time_ms : typing___Optional[builtin___int] = None,
        entities : typing___Optional[typing___Iterable[type___TrendSearchEntity]] = None,
        latency_index_lookup_ms : typing___Optional[builtin___int] = None,
        latency_doc_lookup_ms : typing___Optional[builtin___int] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"entities",b"entities",u"hits_per_page",b"hits_per_page",u"latency_doc_lookup_ms",b"latency_doc_lookup_ms",u"latency_index_lookup_ms",b"latency_index_lookup_ms",u"page",b"page",u"processing_time_ms",b"processing_time_ms",u"total_hits",b"total_hits",u"total_pages",b"total_pages"]) -> None: ...
type___TrendSearchResponse = TrendSearchResponse
