# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import organization_pb2 as organization__pb2
import trend_search_pb2 as trend__search__pb2


class TrendSearchServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTrendSearch = channel.unary_unary(
                '/calixa.domain.trendsearch.TrendSearchService/GetTrendSearch',
                request_serializer=trend__search__pb2.GetTrendSearchRequest.SerializeToString,
                response_deserializer=organization__pb2.TrendSearch.FromString,
                )
        self.GetAllTrendSearches = channel.unary_stream(
                '/calixa.domain.trendsearch.TrendSearchService/GetAllTrendSearches',
                request_serializer=trend__search__pb2.GetTrendSearchRequest.SerializeToString,
                response_deserializer=organization__pb2.TrendSearch.FromString,
                )
        self.PutTrendSearch = channel.unary_unary(
                '/calixa.domain.trendsearch.TrendSearchService/PutTrendSearch',
                request_serializer=trend__search__pb2.PutTrendSearchRequest.SerializeToString,
                response_deserializer=organization__pb2.TrendSearch.FromString,
                )
        self.DeleteTrendSearch = channel.unary_unary(
                '/calixa.domain.trendsearch.TrendSearchService/DeleteTrendSearch',
                request_serializer=trend__search__pb2.DeleteTrendSearchRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class TrendSearchServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTrendSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllTrendSearches(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutTrendSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTrendSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrendSearchServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTrendSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrendSearch,
                    request_deserializer=trend__search__pb2.GetTrendSearchRequest.FromString,
                    response_serializer=organization__pb2.TrendSearch.SerializeToString,
            ),
            'GetAllTrendSearches': grpc.unary_stream_rpc_method_handler(
                    servicer.GetAllTrendSearches,
                    request_deserializer=trend__search__pb2.GetTrendSearchRequest.FromString,
                    response_serializer=organization__pb2.TrendSearch.SerializeToString,
            ),
            'PutTrendSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.PutTrendSearch,
                    request_deserializer=trend__search__pb2.PutTrendSearchRequest.FromString,
                    response_serializer=organization__pb2.TrendSearch.SerializeToString,
            ),
            'DeleteTrendSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTrendSearch,
                    request_deserializer=trend__search__pb2.DeleteTrendSearchRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calixa.domain.trendsearch.TrendSearchService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TrendSearchService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTrendSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calixa.domain.trendsearch.TrendSearchService/GetTrendSearch',
            trend__search__pb2.GetTrendSearchRequest.SerializeToString,
            organization__pb2.TrendSearch.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAllTrendSearches(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/calixa.domain.trendsearch.TrendSearchService/GetAllTrendSearches',
            trend__search__pb2.GetTrendSearchRequest.SerializeToString,
            organization__pb2.TrendSearch.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PutTrendSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calixa.domain.trendsearch.TrendSearchService/PutTrendSearch',
            trend__search__pb2.PutTrendSearchRequest.SerializeToString,
            organization__pb2.TrendSearch.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteTrendSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calixa.domain.trendsearch.TrendSearchService/DeleteTrendSearch',
            trend__search__pb2.DeleteTrendSearchRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
