
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-06-06T10:15:56-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "2d36a30f0a45d74c807dcebf732aefdb42a491d3",
 "version": "0.0.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
