
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-06-08T10:38:52-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "ef5214ff5bde2876119fb0e8a02bdea934a8006e",
 "version": "1.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
