# Generated by Django 4.2 on 2023-06-02 16:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('wagtail_maps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='max_zoom',
        ),
        migrations.RemoveField(
            model_name='map',
            name='min_zoom',
        ),
    ]
