from StrangeSerializerLab3.StrangeXML.StrangeXmlSerializer import StrangeXmlSerializer
from StrangeSerializerLab3.StrangeJSON.StrangeJsonSerializer import StrangeJsonSerializer
from StrangeSerializerLab3.AdditionalFunctions import *

