# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import integration_metadata_pb2 as integration__metadata__pb2


class IntegrationMetadataServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetIntegrationMetadata = channel.unary_unary(
                '/calixa.domain.integrationmetadata.IntegrationMetadataService/GetIntegrationMetadata',
                request_serializer=integration__metadata__pb2.GetIntegrationMetadataRequest.SerializeToString,
                response_deserializer=integration__metadata__pb2.IntegrationMetadata.FromString,
                )
        self.GetAllIntegrationMetadata = channel.unary_unary(
                '/calixa.domain.integrationmetadata.IntegrationMetadataService/GetAllIntegrationMetadata',
                request_serializer=integration__metadata__pb2.GetIntegrationMetadataRequest.SerializeToString,
                response_deserializer=integration__metadata__pb2.GetIntegrationMetadataResponse.FromString,
                )
        self.PutIntegrationMetadata = channel.unary_unary(
                '/calixa.domain.integrationmetadata.IntegrationMetadataService/PutIntegrationMetadata',
                request_serializer=integration__metadata__pb2.PutIntegrationMetadataRequest.SerializeToString,
                response_deserializer=integration__metadata__pb2.IntegrationMetadata.FromString,
                )
        self.DeleteIntegrationMetadata = channel.unary_unary(
                '/calixa.domain.integrationmetadata.IntegrationMetadataService/DeleteIntegrationMetadata',
                request_serializer=integration__metadata__pb2.DeleteIntegrationMetadataRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class IntegrationMetadataServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetIntegrationMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllIntegrationMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutIntegrationMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteIntegrationMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IntegrationMetadataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetIntegrationMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIntegrationMetadata,
                    request_deserializer=integration__metadata__pb2.GetIntegrationMetadataRequest.FromString,
                    response_serializer=integration__metadata__pb2.IntegrationMetadata.SerializeToString,
            ),
            'GetAllIntegrationMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllIntegrationMetadata,
                    request_deserializer=integration__metadata__pb2.GetIntegrationMetadataRequest.FromString,
                    response_serializer=integration__metadata__pb2.GetIntegrationMetadataResponse.SerializeToString,
            ),
            'PutIntegrationMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.PutIntegrationMetadata,
                    request_deserializer=integration__metadata__pb2.PutIntegrationMetadataRequest.FromString,
                    response_serializer=integration__metadata__pb2.IntegrationMetadata.SerializeToString,
            ),
            'DeleteIntegrationMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteIntegrationMetadata,
                    request_deserializer=integration__metadata__pb2.DeleteIntegrationMetadataRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calixa.domain.integrationmetadata.IntegrationMetadataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class IntegrationMetadataService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetIntegrationMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calixa.domain.integrationmetadata.IntegrationMetadataService/GetIntegrationMetadata',
            integration__metadata__pb2.GetIntegrationMetadataRequest.SerializeToString,
            integration__metadata__pb2.IntegrationMetadata.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAllIntegrationMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calixa.domain.integrationmetadata.IntegrationMetadataService/GetAllIntegrationMetadata',
            integration__metadata__pb2.GetIntegrationMetadataRequest.SerializeToString,
            integration__metadata__pb2.GetIntegrationMetadataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PutIntegrationMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calixa.domain.integrationmetadata.IntegrationMetadataService/PutIntegrationMetadata',
            integration__metadata__pb2.PutIntegrationMetadataRequest.SerializeToString,
            integration__metadata__pb2.IntegrationMetadata.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteIntegrationMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calixa.domain.integrationmetadata.IntegrationMetadataService/DeleteIntegrationMetadata',
            integration__metadata__pb2.DeleteIntegrationMetadataRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
