# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from common_pb2 import (
    PredictionTaskValue as common_pb2___PredictionTaskValue,
)

from condition_pb2 import (
    ConditionGroup as condition_pb2___ConditionGroup,
)

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.internal.enum_type_wrapper import (
    _EnumTypeWrapper as google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from google.protobuf.timestamp_pb2 import (
    Timestamp as google___protobuf___timestamp_pb2___Timestamp,
)

from typing import (
    Iterable as typing___Iterable,
    NewType as typing___NewType,
    Optional as typing___Optional,
    Text as typing___Text,
    cast as typing___cast,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

OptimizationObjectiveValue = typing___NewType('OptimizationObjectiveValue', builtin___int)
type___OptimizationObjectiveValue = OptimizationObjectiveValue
OptimizationObjective: _OptimizationObjective
class _OptimizationObjective(google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[OptimizationObjectiveValue]):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    OPTIMIZATION_OBJECTIVE_UNSPECIFIED = typing___cast(OptimizationObjectiveValue, 0)
    OPTIMIZATION_OBJECTIVE_RECALL = typing___cast(OptimizationObjectiveValue, 1)
    OPTIMIZATION_OBJECTIVE_PRECISION = typing___cast(OptimizationObjectiveValue, 2)
    OPTIMIZATION_OBJECTIVE_ROC_AUC = typing___cast(OptimizationObjectiveValue, 3)
OPTIMIZATION_OBJECTIVE_UNSPECIFIED = typing___cast(OptimizationObjectiveValue, 0)
OPTIMIZATION_OBJECTIVE_RECALL = typing___cast(OptimizationObjectiveValue, 1)
OPTIMIZATION_OBJECTIVE_PRECISION = typing___cast(OptimizationObjectiveValue, 2)
OPTIMIZATION_OBJECTIVE_ROC_AUC = typing___cast(OptimizationObjectiveValue, 3)
type___OptimizationObjective = OptimizationObjective

PredictionTaskConfigStateValue = typing___NewType('PredictionTaskConfigStateValue', builtin___int)
type___PredictionTaskConfigStateValue = PredictionTaskConfigStateValue
PredictionTaskConfigState: _PredictionTaskConfigState
class _PredictionTaskConfigState(google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[PredictionTaskConfigStateValue]):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    PREDICTION_TASK_CONFIG_STATE_UNSPECIFIED = typing___cast(PredictionTaskConfigStateValue, 0)
    PREDICTION_TASK_CONFIG_STATE_ENABLED = typing___cast(PredictionTaskConfigStateValue, 1)
    PREDICTION_TASK_CONFIG_STATE_PAUSED = typing___cast(PredictionTaskConfigStateValue, 2)
PREDICTION_TASK_CONFIG_STATE_UNSPECIFIED = typing___cast(PredictionTaskConfigStateValue, 0)
PREDICTION_TASK_CONFIG_STATE_ENABLED = typing___cast(PredictionTaskConfigStateValue, 1)
PREDICTION_TASK_CONFIG_STATE_PAUSED = typing___cast(PredictionTaskConfigStateValue, 2)
type___PredictionTaskConfigState = PredictionTaskConfigState

class FeatureAttribution(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    feature: typing___Text = ...
    attribution: builtin___float = ...

    def __init__(self,
        *,
        feature : typing___Optional[typing___Text] = None,
        attribution : typing___Optional[builtin___float] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"attribution",b"attribution",u"feature",b"feature"]) -> None: ...
type___FeatureAttribution = FeatureAttribution

class ModelMetric(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    threshold: builtin___float = ...
    recall: builtin___float = ...
    precision: builtin___float = ...
    false_positive_rate: builtin___float = ...
    true_positives: builtin___int = ...
    false_positives: builtin___int = ...
    true_negatives: builtin___int = ...
    false_negatives: builtin___int = ...

    def __init__(self,
        *,
        threshold : typing___Optional[builtin___float] = None,
        recall : typing___Optional[builtin___float] = None,
        precision : typing___Optional[builtin___float] = None,
        false_positive_rate : typing___Optional[builtin___float] = None,
        true_positives : typing___Optional[builtin___int] = None,
        false_positives : typing___Optional[builtin___int] = None,
        true_negatives : typing___Optional[builtin___int] = None,
        false_negatives : typing___Optional[builtin___int] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"false_negatives",b"false_negatives",u"false_positive_rate",b"false_positive_rate",u"false_positives",b"false_positives",u"precision",b"precision",u"recall",b"recall",u"threshold",b"threshold",u"true_negatives",b"true_negatives",u"true_positives",b"true_positives"]) -> None: ...
type___ModelMetric = ModelMetric

class BigFishPredictionTaskConfig(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    optimization_objective: type___OptimizationObjectiveValue = ...
    threshold: builtin___float = ...

    @property
    def true_positive_labels(self) -> condition_pb2___ConditionGroup: ...

    @property
    def true_negative_labels(self) -> condition_pb2___ConditionGroup: ...

    def __init__(self,
        *,
        optimization_objective : typing___Optional[type___OptimizationObjectiveValue] = None,
        threshold : typing___Optional[builtin___float] = None,
        true_positive_labels : typing___Optional[condition_pb2___ConditionGroup] = None,
        true_negative_labels : typing___Optional[condition_pb2___ConditionGroup] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"true_negative_labels",b"true_negative_labels",u"true_positive_labels",b"true_positive_labels"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"optimization_objective",b"optimization_objective",u"threshold",b"threshold",u"true_negative_labels",b"true_negative_labels",u"true_positive_labels",b"true_positive_labels"]) -> None: ...
type___BigFishPredictionTaskConfig = BigFishPredictionTaskConfig

class PredictionTaskConfig(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    organization_id: typing___Text = ...
    prediction_task: common_pb2___PredictionTaskValue = ...
    state: type___PredictionTaskConfigStateValue = ...

    @property
    def big_fish(self) -> type___BigFishPredictionTaskConfig: ...

    @property
    def created_at(self) -> google___protobuf___timestamp_pb2___Timestamp: ...

    @property
    def updated_at(self) -> google___protobuf___timestamp_pb2___Timestamp: ...

    @property
    def deleted_at(self) -> google___protobuf___timestamp_pb2___Timestamp: ...

    def __init__(self,
        *,
        organization_id : typing___Optional[typing___Text] = None,
        prediction_task : typing___Optional[common_pb2___PredictionTaskValue] = None,
        state : typing___Optional[type___PredictionTaskConfigStateValue] = None,
        big_fish : typing___Optional[type___BigFishPredictionTaskConfig] = None,
        created_at : typing___Optional[google___protobuf___timestamp_pb2___Timestamp] = None,
        updated_at : typing___Optional[google___protobuf___timestamp_pb2___Timestamp] = None,
        deleted_at : typing___Optional[google___protobuf___timestamp_pb2___Timestamp] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"big_fish",b"big_fish",u"config",b"config",u"created_at",b"created_at",u"deleted_at",b"deleted_at",u"updated_at",b"updated_at"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"big_fish",b"big_fish",u"config",b"config",u"created_at",b"created_at",u"deleted_at",b"deleted_at",u"organization_id",b"organization_id",u"prediction_task",b"prediction_task",u"state",b"state",u"updated_at",b"updated_at"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions___Literal[u"config",b"config"]) -> typing_extensions___Literal["big_fish"]: ...
type___PredictionTaskConfig = PredictionTaskConfig

class Model(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    organization_id: typing___Text = ...
    prediction_task: common_pb2___PredictionTaskValue = ...
    version: typing___Text = ...
    table_name: typing___Text = ...
    ideal_threshold: builtin___float = ...

    @property
    def global_feature_attributions(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___FeatureAttribution]: ...

    @property
    def metrics(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___ModelMetric]: ...

    @property
    def created_at(self) -> google___protobuf___timestamp_pb2___Timestamp: ...

    @property
    def updated_at(self) -> google___protobuf___timestamp_pb2___Timestamp: ...

    @property
    def deleted_at(self) -> google___protobuf___timestamp_pb2___Timestamp: ...

    @property
    def expires_at(self) -> google___protobuf___timestamp_pb2___Timestamp: ...

    def __init__(self,
        *,
        organization_id : typing___Optional[typing___Text] = None,
        prediction_task : typing___Optional[common_pb2___PredictionTaskValue] = None,
        version : typing___Optional[typing___Text] = None,
        table_name : typing___Optional[typing___Text] = None,
        ideal_threshold : typing___Optional[builtin___float] = None,
        global_feature_attributions : typing___Optional[typing___Iterable[type___FeatureAttribution]] = None,
        metrics : typing___Optional[typing___Iterable[type___ModelMetric]] = None,
        created_at : typing___Optional[google___protobuf___timestamp_pb2___Timestamp] = None,
        updated_at : typing___Optional[google___protobuf___timestamp_pb2___Timestamp] = None,
        deleted_at : typing___Optional[google___protobuf___timestamp_pb2___Timestamp] = None,
        expires_at : typing___Optional[google___protobuf___timestamp_pb2___Timestamp] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"created_at",b"created_at",u"deleted_at",b"deleted_at",u"expires_at",b"expires_at",u"updated_at",b"updated_at"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"created_at",b"created_at",u"deleted_at",b"deleted_at",u"expires_at",b"expires_at",u"global_feature_attributions",b"global_feature_attributions",u"ideal_threshold",b"ideal_threshold",u"metrics",b"metrics",u"organization_id",b"organization_id",u"prediction_task",b"prediction_task",u"table_name",b"table_name",u"updated_at",b"updated_at",u"version",b"version"]) -> None: ...
type___Model = Model

class GetCurrentModelRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    prediction_task: common_pb2___PredictionTaskValue = ...

    def __init__(self,
        *,
        prediction_task : typing___Optional[common_pb2___PredictionTaskValue] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"prediction_task",b"prediction_task"]) -> None: ...
type___GetCurrentModelRequest = GetCurrentModelRequest

class GetPredictionTaskConfigRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    prediction_task: common_pb2___PredictionTaskValue = ...

    def __init__(self,
        *,
        prediction_task : typing___Optional[common_pb2___PredictionTaskValue] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"prediction_task",b"prediction_task"]) -> None: ...
type___GetPredictionTaskConfigRequest = GetPredictionTaskConfigRequest

class LearningWorkflowNotification(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    organization_id: typing___Text = ...
    prediction_task: common_pb2___PredictionTaskValue = ...
    labels_table_name: typing___Text = ...
    feature_vectors_table_name: typing___Text = ...
    model_table_name: typing___Text = ...
    predictions_table_name: typing___Text = ...
    cursor: typing___Text = ...
    shadow_scores: builtin___bool = ...

    @property
    def results_ready_at(self) -> google___protobuf___timestamp_pb2___Timestamp: ...

    def __init__(self,
        *,
        organization_id : typing___Optional[typing___Text] = None,
        prediction_task : typing___Optional[common_pb2___PredictionTaskValue] = None,
        labels_table_name : typing___Optional[typing___Text] = None,
        feature_vectors_table_name : typing___Optional[typing___Text] = None,
        model_table_name : typing___Optional[typing___Text] = None,
        predictions_table_name : typing___Optional[typing___Text] = None,
        cursor : typing___Optional[typing___Text] = None,
        results_ready_at : typing___Optional[google___protobuf___timestamp_pb2___Timestamp] = None,
        shadow_scores : typing___Optional[builtin___bool] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"results_ready_at",b"results_ready_at"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"cursor",b"cursor",u"feature_vectors_table_name",b"feature_vectors_table_name",u"labels_table_name",b"labels_table_name",u"model_table_name",b"model_table_name",u"organization_id",b"organization_id",u"prediction_task",b"prediction_task",u"predictions_table_name",b"predictions_table_name",u"results_ready_at",b"results_ready_at",u"shadow_scores",b"shadow_scores"]) -> None: ...
type___LearningWorkflowNotification = LearningWorkflowNotification

class Prediction(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    predicted_label: builtin___bool = ...
    probability: builtin___float = ...

    @property
    def feature_attributions(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___FeatureAttribution]: ...

    def __init__(self,
        *,
        predicted_label : typing___Optional[builtin___bool] = None,
        probability : typing___Optional[builtin___float] = None,
        feature_attributions : typing___Optional[typing___Iterable[type___FeatureAttribution]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"feature_attributions",b"feature_attributions",u"predicted_label",b"predicted_label",u"probability",b"probability"]) -> None: ...
type___Prediction = Prediction

class Label(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    organization_id: typing___Text = ...
    prediction_task: common_pb2___PredictionTaskValue = ...
    canonical_id: typing___Text = ...
    positive: builtin___bool = ...
    created_by: typing___Text = ...

    @property
    def created_at(self) -> google___protobuf___timestamp_pb2___Timestamp: ...

    @property
    def updated_at(self) -> google___protobuf___timestamp_pb2___Timestamp: ...

    @property
    def deleted_at(self) -> google___protobuf___timestamp_pb2___Timestamp: ...

    def __init__(self,
        *,
        organization_id : typing___Optional[typing___Text] = None,
        prediction_task : typing___Optional[common_pb2___PredictionTaskValue] = None,
        canonical_id : typing___Optional[typing___Text] = None,
        positive : typing___Optional[builtin___bool] = None,
        created_by : typing___Optional[typing___Text] = None,
        created_at : typing___Optional[google___protobuf___timestamp_pb2___Timestamp] = None,
        updated_at : typing___Optional[google___protobuf___timestamp_pb2___Timestamp] = None,
        deleted_at : typing___Optional[google___protobuf___timestamp_pb2___Timestamp] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"created_at",b"created_at",u"deleted_at",b"deleted_at",u"updated_at",b"updated_at"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"canonical_id",b"canonical_id",u"created_at",b"created_at",u"created_by",b"created_by",u"deleted_at",b"deleted_at",u"organization_id",b"organization_id",u"positive",b"positive",u"prediction_task",b"prediction_task",u"updated_at",b"updated_at"]) -> None: ...
type___Label = Label

class GetLabelRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    canonical_id: typing___Text = ...
    prediction_task: common_pb2___PredictionTaskValue = ...

    def __init__(self,
        *,
        canonical_id : typing___Optional[typing___Text] = None,
        prediction_task : typing___Optional[common_pb2___PredictionTaskValue] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"canonical_id",b"canonical_id",u"prediction_task",b"prediction_task"]) -> None: ...
type___GetLabelRequest = GetLabelRequest

class DeleteLabelRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    canonical_id: typing___Text = ...
    prediction_task: common_pb2___PredictionTaskValue = ...

    def __init__(self,
        *,
        canonical_id : typing___Optional[typing___Text] = None,
        prediction_task : typing___Optional[common_pb2___PredictionTaskValue] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"canonical_id",b"canonical_id",u"prediction_task",b"prediction_task"]) -> None: ...
type___DeleteLabelRequest = DeleteLabelRequest
