# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ovmsclient/tfs_compat/protos/tensorflow_serving/apis/get_model_metadata.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from ovmsclient.tfs_compat.protos.tensorflow.core.protobuf import meta_graph_pb2 as ovmsclient_dot_tfs__compat_dot_protos_dot_tensorflow_dot_core_dot_protobuf_dot_meta__graph__pb2
from ovmsclient.tfs_compat.protos.tensorflow_serving.apis import model_pb2 as ovmsclient_dot_tfs__compat_dot_protos_dot_tensorflow__serving_dot_apis_dot_model__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nMovmsclient/tfs_compat/protos/tensorflow_serving/apis/get_model_metadata.proto\x12\x12ovmsclient.serving\x1a\x19google/protobuf/any.proto\x1a\x46ovmsclient/tfs_compat/protos/tensorflow/core/protobuf/meta_graph.proto\x1a@ovmsclient/tfs_compat/protos/tensorflow_serving/apis/model.proto\"\xae\x01\n\x0fSignatureDefMap\x12L\n\rsignature_def\x18\x01 \x03(\x0b\x32\x35.ovmsclient.serving.SignatureDefMap.SignatureDefEntry\x1aM\n\x11SignatureDefEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\'\n\x05value\x18\x02 \x01(\x0b\x32\x18.ovmsclient.SignatureDef:\x02\x38\x01\"d\n\x17GetModelMetadataRequest\x12\x31\n\nmodel_spec\x18\x01 \x01(\x0b\x32\x1d.ovmsclient.serving.ModelSpec\x12\x16\n\x0emetadata_field\x18\x02 \x03(\t\"\xe2\x01\n\x18GetModelMetadataResponse\x12\x31\n\nmodel_spec\x18\x01 \x01(\x0b\x32\x1d.ovmsclient.serving.ModelSpec\x12L\n\x08metadata\x18\x02 \x03(\x0b\x32:.ovmsclient.serving.GetModelMetadataResponse.MetadataEntry\x1a\x45\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any:\x02\x38\x01\x42\x03\xf8\x01\x01\x62\x06proto3')



_SIGNATUREDEFMAP = DESCRIPTOR.message_types_by_name['SignatureDefMap']
_SIGNATUREDEFMAP_SIGNATUREDEFENTRY = _SIGNATUREDEFMAP.nested_types_by_name['SignatureDefEntry']
_GETMODELMETADATAREQUEST = DESCRIPTOR.message_types_by_name['GetModelMetadataRequest']
_GETMODELMETADATARESPONSE = DESCRIPTOR.message_types_by_name['GetModelMetadataResponse']
_GETMODELMETADATARESPONSE_METADATAENTRY = _GETMODELMETADATARESPONSE.nested_types_by_name['MetadataEntry']
SignatureDefMap = _reflection.GeneratedProtocolMessageType('SignatureDefMap', (_message.Message,), {

  'SignatureDefEntry' : _reflection.GeneratedProtocolMessageType('SignatureDefEntry', (_message.Message,), {
    'DESCRIPTOR' : _SIGNATUREDEFMAP_SIGNATUREDEFENTRY,
    '__module__' : 'ovmsclient.tfs_compat.protos.tensorflow_serving.apis.get_model_metadata_pb2'
    # @@protoc_insertion_point(class_scope:ovmsclient.serving.SignatureDefMap.SignatureDefEntry)
    })
  ,
  'DESCRIPTOR' : _SIGNATUREDEFMAP,
  '__module__' : 'ovmsclient.tfs_compat.protos.tensorflow_serving.apis.get_model_metadata_pb2'
  # @@protoc_insertion_point(class_scope:ovmsclient.serving.SignatureDefMap)
  })
_sym_db.RegisterMessage(SignatureDefMap)
_sym_db.RegisterMessage(SignatureDefMap.SignatureDefEntry)

GetModelMetadataRequest = _reflection.GeneratedProtocolMessageType('GetModelMetadataRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETMODELMETADATAREQUEST,
  '__module__' : 'ovmsclient.tfs_compat.protos.tensorflow_serving.apis.get_model_metadata_pb2'
  # @@protoc_insertion_point(class_scope:ovmsclient.serving.GetModelMetadataRequest)
  })
_sym_db.RegisterMessage(GetModelMetadataRequest)

GetModelMetadataResponse = _reflection.GeneratedProtocolMessageType('GetModelMetadataResponse', (_message.Message,), {

  'MetadataEntry' : _reflection.GeneratedProtocolMessageType('MetadataEntry', (_message.Message,), {
    'DESCRIPTOR' : _GETMODELMETADATARESPONSE_METADATAENTRY,
    '__module__' : 'ovmsclient.tfs_compat.protos.tensorflow_serving.apis.get_model_metadata_pb2'
    # @@protoc_insertion_point(class_scope:ovmsclient.serving.GetModelMetadataResponse.MetadataEntry)
    })
  ,
  'DESCRIPTOR' : _GETMODELMETADATARESPONSE,
  '__module__' : 'ovmsclient.tfs_compat.protos.tensorflow_serving.apis.get_model_metadata_pb2'
  # @@protoc_insertion_point(class_scope:ovmsclient.serving.GetModelMetadataResponse)
  })
_sym_db.RegisterMessage(GetModelMetadataResponse)
_sym_db.RegisterMessage(GetModelMetadataResponse.MetadataEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\370\001\001'
  _SIGNATUREDEFMAP_SIGNATUREDEFENTRY._options = None
  _SIGNATUREDEFMAP_SIGNATUREDEFENTRY._serialized_options = b'8\001'
  _GETMODELMETADATARESPONSE_METADATAENTRY._options = None
  _GETMODELMETADATARESPONSE_METADATAENTRY._serialized_options = b'8\001'
  _SIGNATUREDEFMAP._serialized_start=267
  _SIGNATUREDEFMAP._serialized_end=441
  _SIGNATUREDEFMAP_SIGNATUREDEFENTRY._serialized_start=364
  _SIGNATUREDEFMAP_SIGNATUREDEFENTRY._serialized_end=441
  _GETMODELMETADATAREQUEST._serialized_start=443
  _GETMODELMETADATAREQUEST._serialized_end=543
  _GETMODELMETADATARESPONSE._serialized_start=546
  _GETMODELMETADATARESPONSE._serialized_end=772
  _GETMODELMETADATARESPONSE_METADATAENTRY._serialized_start=703
  _GETMODELMETADATARESPONSE_METADATAENTRY._serialized_end=772
# @@protoc_insertion_point(module_scope)
