# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/proofs',
                'doc_host': 'https://maxtheman.github.io',
                'git_url': 'https://github.com/maxtheman/proofs',
                'lib_path': 'proofs'},
  'syms': { 'proofs.assistant': {},
            'proofs.core': { 'proofs.core.constant': ('core.html#constant', 'proofs/core.py'),
                             'proofs.core.contradiction_proof': ('core.html#contradiction_proof', 'proofs/core.py'),
                             'proofs.core.equals': ('core.html#equals', 'proofs/core.py'),
                             'proofs.core.equation': ('core.html#equation', 'proofs/core.py'),
                             'proofs.core.make_examples': ('core.html#make_examples', 'proofs/core.py'),
                             'proofs.core.not_equals': ('core.html#not_equals', 'proofs/core.py'),
                             'proofs.core.prove': ('core.html#prove', 'proofs/core.py'),
                             'proofs.core.variable': ('core.html#variable', 'proofs/core.py')}}}
